on:
  workflow_run:
    workflows:
      - test1
      - test2
    types: [ completed ]

jobs:
  comment-failures:
    runs-on: ubuntu-latest
    env:
      A2IKM_GITHUB_API_TOKEN: ${{secrets.A2IKM_GITHUB_API_TOKEN}}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      - run: env
      - run: echo '${{ toJSON(github.event) }}'
      - run: bash .github/scripts/comment-failures.sh
