on:
  workflow_run:
    workflows:
      - test1
      - test2
      - test3
    types: [ completed ]

name: comment-failures

jobs:
  comment-failures:
    runs-on: ubuntu-latest
    env:
      API_TOKEN: ${{ secrets.A2IKM_GITHUB_API_TOKEN }}
      HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
      HEAD_COMMIT: ${{ github.event.workflow_run.head_commit.id }}
      WORKFLOW: ${{ github.event.workflow.name }}
      CHECK_SUITE_ID: ${{ github.event.workflow_run.check_suite_id }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler: none
      - run: ruby .github/scripts/comment-failures.rb
